FROM python:2-alpine
MAINTAINER Nathan Coleman "nathan@ncmn.me"
RUN apk update
RUN apk add --virtual build-deps gcc python-dev musl-dev
RUN apk add --update git postgresql-dev
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]
