CREATE_SESSION_URL = '/session/create/'
HELLO_URL = '/'
REGISTER_URL = '/register/'
REGISTER_WITH_PROVIDER_URL = '/register/<provider_id>/'
VIEW_SESSION_URL = '/session/<session_name>/'
VIEW_SUBMIT_URL = '/session/<session_name>/submit/'
