CREATE_SEASON_URL = '/season/create/'
HELLO_URL = '/'
LOGIN_URL = '/login/'
LOGOUT_URL = '/logout/'
REGISTER_URL = '/register/'
REGISTER_WITH_PROVIDER_URL = '/register/<provider_id>/'
VIEW_SEASON_URL = '/season/<season_name>/'
VIEW_SUBMIT_URL = '/season/<season_name>/submit/'
